apiVersion: apps/v1
kind: Deployment
metadata:
  name:  academydb
  labels:
    app:  db01
spec:
  selector:
    matchLabels:
      app: db01
  replicas: 1
  template:
    metadata:
      labels:
        app:  db01
    spec:
      # initContainers:
      # Init containers are exactly like regular containers, except:
      # - Init containers always run to completion.
      # - Each init container must complete successfully before the next one starts.
      containers:
        - name:  db01
          image:  innovativeacademy/academydb
          args:
            - "--ignore-db-dir=lost+found"
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: academydb-data
          ports:
            - name: db01-port
              containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
              secretKeyRef:
                name: app-secret
                key: db-pass
      nodeSelector:
        zone: ap-south-1a
      volumes:
       - name: db01-data
         awsElasticBlockStore:
          volumeID:  <paste the ID>
          fsType: ext4
# create a tag for EBS volume name kubernetescluster value clustername
