apiVersion: v1
kind: Service
metadata:
  name: db01
spec:
  ports:
    - name: DB01PORT
      protocol: TCP
      port: 3306
      targetPort: db01-port
      # If you set the `spec.type` field to `NodePort` and you want a specific port number,
      # you can specify a value in the `spec.ports[*].nodePort` field.
  selector:
    app: db01